---
- name: install postfix
  apt: name=postfix state=latest
  tags: 
    - postfix
    - mail
- name: install postfix-pgsql
  apt: name=postfix state=latest
  tags: 
    - postfix
    - mail
    - postgres
    - databases
- name: template postfix main.cf
  template: src=postfix/main.cf.j2 dest=/etc/postfix/main.cf
  tags: 
    - postfix
    - mail
    - configs

- name: template postfix master.cf
  template: src=postfix/master.cf.j2 dest=/etc/postfix/master.cf
  tags:   
    - postfix
    - mail
    - configs

- name: templates postfix postgres
  template: src={{ playbook_dir }}/roles/mail/templates/postfix/{{ item }}.cf.j2 dest=/etc/postfix/{{ item }}.cf
  with_items: 
    - 'relay_domains'
    - 'virtual_alias_map'
    - 'virtual_domain_maps'
    - 'virtual_mailbox_limits'
    - 'virtual_mailbox_maps'
  tags:
    - postfix
    - mail
    - configs
    - postgres
