---
- name: install postfix
  apt: name=postfix state=latest
  tags: 
    - postfix
    - mail
- name: install postfix-pgsql
  apt: name=postfix state=latest
  tags: 
    - postfix
    - mail
    - postgres
    - databases
- name: template postfix main.cf
  template: src=postfix/main.cf.j2 dest=/etc/postfix/main.cf
  tags: 
    - postfix
    - mail
    - config
- name: template postfix master.cf
  template: src=postfix/master.cf.j2 dest=/etc/postfix/master.cf
  tags:   
    - postfix
    - mail
    - config
