---
- hosts: ffhh
  roles:
    - basics
    - basics-ffhh
  tags: basics

- hosts: nginx
  roles:
    - nginx
    - nginx-ffhh
    - error-pages
  tags: nginx

- hosts: certbot
  roles:
    - certbot
  tags: certbot

- hosts: certsync
  roles:
    - certsync
  tags: certsync
