---
- hosts: ffhh
  roles:
    - alxndr42.commons.basics
    - basics-ffhh
  tags: basics

- hosts: nginx
  roles:
    - alxndr42.commons.nginx
    - nginx-ffhh
    - error-pages
  tags: nginx

- hosts: nodejs
  roles:
    - alxndr42.commons.nodejs
  tags: nodejs

- hosts: certbot
  roles:
    - alxndr42.commons.certbot
  tags: certbot

- hosts: certsync
  roles:
    - certsync
  tags: certsync
