---
- hosts: ffhh
  roles:
    - basics
    - ffhh-basics
  tags: basics

- hosts: certbot
  roles:
    - certbot
  tags: certbot

- hosts: certsync
  roles:
    - certsync
  tags: certsync

- hosts: nginx
  roles:
    - nginx
  tags: nginx
