---
- hosts: hopglass-frontend
  roles:
    - hopglass-frontend

- hosts: services
  roles:
    - ntp-server

- hosts: media
  roles:
    - website/media
  tags: media

- hosts: updates
  roles:
    - website/updates
  tags: updates
