---
- include: "{{ playbook_dir }}/roles/website/includes/base-static/tasks/main.yml"
  vars:
    site: ffnord_site
    domains:
      - ffnord.net
      - www.ffnord.net
      - nord.freifunk.net
    ports:
      - { number: 80, ssl: false }
    document_root: { path: /var/www/ffnord/site/site, create: false }
    listing: false

- name: clone ffnord.net repository
  git: repo=https://github.com/ffnord/ffnord.net.git dest=/var/www/ffnord/site
  tags:
    - nginx
    - website
    - ffnord

