---
- name: install certbot
  apt:
    name: certbot
    cache_valid_time: 86400

- name: create webroot directory
  file:
    path: /var/www/_acme-challenge
    state: directory

- name: copy cli.ini
  copy:
    src: cli.ini
    dest: /etc/letsencrypt/

- name: populate service facts
  service_facts:

- name: copy reload-nginx hook
  copy:
    src: reload-nginx
    dest: /etc/letsencrypt/renewal-hooks/post/
    mode: 0755
  when: "'nginx' in services"
