---
- name: create ffupdates user
  user:
    name: ffupdates

- name: create updates root
  file:
    path: "{{ updates_root }}"
    owner: "{{ updates_owner }}"
    group: "{{ updates_group }}"
    state: directory

- name: template site
  template:
    src: updates
    dest: /etc/nginx/sites-available/
  notify: reload nginx

- name: enable site
  file:
    src: /etc/nginx/sites-available/updates
    dest: /etc/nginx/sites-enabled/updates
    state: link
  notify: reload nginx
