---
- name: create ffupdates user
  user:
    name: ffupdates

- name: create updates root
  file:
    path: "{{ updates_root }}"
    owner: "{{ updates_owner }}"
    group: "{{ updates_owner }}"
    state: directory

- name: template site
  template:
    src: templates/site.j2
    dest: /etc/nginx/sites-available/{{ site }}
  notify: reload nginx

- name: enable site
  file:
    src: /etc/nginx/sites-available/{{ site }}
    dest: /etc/nginx/sites-enabled/{{ site }}
    state: link
  notify: reload nginx
