---
- name: install dovecot
  apt: name=dovecot state=latest
  tags: 
    - dovecot
    - mail
- name: install dovecot-lmtpd
  apt: name=dovecot-lmtpd state=latest
  tags: 
    - dovecot
    - mail
    - database
    - postgres
    - postgresql
- name: install dovecot-pgsql
  apt: name=dovecot-pgsql state=latest
  tags: 
    - dovecot
    - mail
    - database
    - postgres
    - postgresql
