---
- name: install postfix
  apt: name=postfix state=latest
  tags: 
    - postfix
    - mail
- name: install postfix-pgsql
  apt: name=postfix state=latest
  tags: 
    - postfix
    - mail
    - postgres
    - databases
