---
- include: ../../includes/base-static/tasks/main.yml
  vars:
    site: ffhh_meta
    domains:
      - meta.hamburg.freifunk.net
    ports:
      - { number: 80, ssl: false }
      - { number: 443, ssl: true }
    document_root: { path: /var/www/ffhh/meta, create: true }
    listing: true

