---
- name: run apt-get update
  apt: update_cache=yes
  tags:
    - common
    - packages
    - apt

- name: install common packages
  apt: name={{ item }} state=latest
  with_items:
    - aptitude
    - curl
    - git
    - mosh
    - nano
    - python
    - screen
    - tmux
    - vim
    - wget
    - zsh
  tags:
    - common
    - packages
    - apt

- name: set message of the day
  template: >
    src=etc/motd.j2
    dest=/etc/motd
    mode=0444
    owner=root
    group=root
  tags:
    - common
    - motd
