---
- name: install requirements for some Ansible operations
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - aptitude
    - python-apt
