---
- name: purge vim-tiny
  apt:
    name: vim-tiny
    state: absent
    purge: yes

- name: install user sanity packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ user_sanity_packages }}"

- name: check for /etc/screenrc
  stat: path=/etc/screenrc
  register: f

- name: disable screen startup message
  lineinfile:
    dest: /etc/screenrc
    regexp: '^#(startup_message off)$'
    line: '\1'
    backrefs: yes
    backup: yes
  when: f.stat.exists
