---
- name: install ntpd
  apt:
    name: ntp
    state: present
  tags: ntp

- name: template ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    backup: yes
  notify: restart ntpd
  tags: ntp

- name: start and enable ntpd
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
