---
- name: be sure ntp is installed
  apt: name=ntp state=latest
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntp state=started enabled=yes
  tags: ntp
