---
- name: install dovecot
  apt: name=dovecot-core state=latest
  tags:
    - dovecot
    - mail

- name: install dovecot modules
  apt: name={{ item }} state=latest
  with_items:
    - "dovecot-imapd"
  tags:
    - dovecot
    - mail

- name: install dovecot postgres modules
  apt: name={{ item }} state=latest
  with_items:
    - "dovecot-lmtpd"
    - "dovecot-pgsql"
  tags:
    - dovecot
    - mail
    - database
    - postgres
    - postgresql

- name: create dovecot dir if nonexistent
  file: path=/etc/dovecot state=directory mode=0755
  tags:
    - dovecot
    - mail
    - configs
    - postgres
    - database
    - postgresql

- name: create dovecot conf.d dir if nonexistent
  file: path=/etc/dovecot/conf.d state=directory mode=0755
  tags:
    - dovecot
    - mail
    - configs
    - postgres
    - database
    - postgresql

- name: template dovecot-sql.conf.ext
  template: src={{ playbook_dir }}/roles/mail/templates/dovecot/dovecot-sql.conf.ext.j2 dest=/etc/dovecot/dovecot-sql.conf.ext
  tags:
    - dovecot
    - mail
    - database
    - postgresql
    - postgres
    - configs

- name: template dovecot others
  template: src={{ playbook_dir }}/roles/mail/templates/dovecot/10-{{ item }}.conf.j2 dest=/etc/dovecot/conf.d/10-{{ item }}.conf
  with_items:
  - "auth"
  - "mail"
  - "master"
  - "ssl"
  tags:
    - dovecot
    - mail
    - configs
