---
- name: install dovecot
  apt: name=dovecot-core state=latest
  tags: 
    - dovecot
    - mail
- name: install dovecot modules
  apt: name={{ item }} state=latest
  with_items:
    - "dovecot-imapd"
  tags:
    - dovecot
    - mail
- name: install dovecot postgres modules
  apt: name={{ items }} state=latest
  with_item:
    - "dovecot-lmtpd"
    - "dovecot-pgsql"
  tags: 
    - dovecot
    - mail
    - database
    - postgres
    - postgresql
