---
- name: install popular user packages
  apt:
    name:
      - mosh
      - nano
      - wget
      - zsh
    state: present

- name: copy new-user script
  copy:
    src: new-user
    dest: /usr/local/sbin
    owner: root
    group: root
    mode: 0550
