---
- name: install popular user packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mosh
    - nano
    - wget
    - zsh

- name: copy new-user script
  copy:
    src: new-user
    dest: /usr/local/sbin
    owner: root
    group: root
    mode: 0550
